docs/sdks/api/user/setUserListener.mdx, docs/sdks/callback/onUserStatusChanged.mdx, docs/sdks/listener/userListener.mdx
=> Added 'onUserStatusChanged' callback function.

docs/sdks/enum/messageContentType.mdx
=> no message

docs/sdks/callback/onGroupDismissed.mdx
=> Update 'onGroupDismissed' callback function.

docs/sdks/enum/groupType.mdx, docs/sdks/enum/roleLevel.mdx
=> Update group type and permission enumeration.

docs/sdks/api/message/index.mdx, docs/sdks/api/message/setMessageLocalEx.mdx, docs/sdks/api/user/getSubscribeUsersStatus.mdx, docs/sdks/api/user/getUserStatus.mdx, docs/sdks/api/user/getUsersInfoStranger.mdx, docs/sdks/api/user/index.mdx, docs/sdks/api/user/subscribeUsersStatus.mdx, docs/sdks/api/user/unsubscribeUsersStatus.mdx, docs/sdks/callback/onUserStatusChanged.mdx
=> feat: Add documents related to user online status.

docs/sdks/api/group/setGroupMemberInfo.mdx, docs/sdks/api/message/createImageMessageByURL.mdx, docs/sdks/api/message/createTextAtAllMessage.mdx, docs/sdks/api/message/setBatchMsgListener.mdx, docs/sdks/callback/onConnectFailed.mdx, docs/sdks/callback/onConnectSuccess.mdx, docs/sdks/callback/onConnecting.mdx, docs/sdks/callback/onError.mdx, docs/sdks/callback/onKickedOffline.mdx, docs/sdks/callback/onProgress.mdx, docs/sdks/callback/onRecvNewMessages.mdx, docs/sdks/callback/onRecvOfflineNewMessage.mdx, docs/sdks/callback/onRecvOfflineNewMessages.mdx, docs/sdks/callback/onUserTokenExpired.mdx, docs/sdks/class/init/config.mdx, docs/sdks/enum/handleResult.mdx, docs/sdks/enum/joinSource.mdx, docs/sdks/enum/loginStatus.mdx, docs/sdks/enum/messageContentType.mdx, docs/sdks/enum/messageStatus.mdx, docs/sdks/enum/platform.mdx, docs/sdks/enum/recvMsgOpt.mdx, docs/sdks/enum/relationship.mdx
=> fix: Delete some useless tabs.

docs/sdks/callback/onConnectFailed.mdx, docs/sdks/callback/onConnectSuccess.mdx, docs/sdks/callback/onConnecting.mdx, docs/sdks/callback/onKickedOffline.mdx, docs/sdks/callback/onProgress.mdx, docs/sdks/callback/onSuccess.mdx, docs/sdks/callback/onUserTokenExpired.mdx, docs/sdks/enum/messageContentType.mdx
=> fix: Fixed some issues. (#42)

docs/restapi/apis/friendsManagement/addBlackList.mdx, docs/restapi/apis/friendsManagement/updateFriends.mdx, docs/restapi/apis/groupManagement/joinGroup.mdx, docs/restapi/apis/userManagement/updateUserInfo.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/addBlackList.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/updateFriends.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/groupManagement/joinGroup.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateUserInfo.mdx
=> update rest api ex field

docs/guides/gettingStarted/admin.mdx, i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/admin.mdx
=> fix:fix mdx

.github/workflows/main-ci.yaml
<br>
Additionally, the npm version has been updated to the latest release. 
Fixes #37
=> feat: add openim docs update node version: latest

docs/restapi/apis/conversationManagement/getConversationList.mdx, docs/restapi/apis/userManagement/addNotificationAccount.mdx, docs/restapi/apis/userManagement/searchNotificationAccount.mdx, docs/restapi/apis/userManagement/updateNotificationAccount.mdx, docs/restapi/webhooks/example.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/conversationManagement/getConversationList.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/addNotificationAccount.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/searchNotificationAccount.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateNotificationAccount.mdx
=> fix: fix the notificationAccounts docs error

docs/restapi/apis/conversationManagement/getConversationList.mdx, docs/restapi/apis/userManagement/searchNotificationAccount.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/conversationManagement/getConversationList.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/searchNotificationAccount.mdx
=> fix: fix the getConversation docs error

docs/restapi/apis/conversationManagement/getSortedConversationList.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/conversationManagement/getSortedConversationList.mdx
=> fix: fix the getSortedConversationList docs

i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/example.mdx
=> fix: fix the webhook en docs

docs/guides/gettingStarted/nginxDomainConfig.mdx, docs/restapi/webhooks/msg/sendSingleMsgAfter.mdx, i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/nginxDomainConfig.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/msg/sendSingleMsgAfter.mdx
=> feat: add the nginxDomainConfig en docs and fix some unclean context

docs/sdks/api/message/createImageMessageByURL.mdx, i18n/en/docusaurus-plugin-content-docs-sdks/current/api/message/createImageMessageByURL.mdx
=> fix: func name in web tab

docs/guides/gettingStarted/mac-deployment-guide.mdx, i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/mac-deployment-guide.mdx
=> docs(mac-deployment-guide.mdx): create openim mac source deployment docs

docs/sdks/quickstart/uniapp.mdx, i18n/en/docusaurus-plugin-content-docs-sdks/current/quickstart/uniapp.mdx
=> doc: uniapp quickstart doc update

docs/restapi/apis/authenticationManagement/getUserToken.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/authenticationManagement/getUserToken.mdx
=> fix: del the old Admin userID

docs/sdks/quickstart/reactNative.mdx, i18n/en/docusaurus-plugin-content-docs-sdks/current/quickstart/reactNative.mdx
=> feat: update rn sdk doc

docs/sdks/api/user/getUsersInfoWithCache.mdx, i18n/en/docusaurus-plugin-content-docs-sdks/current/api/user/getUsersInfoWithCache.mdx
=> fix: update getUsersInfoWithCache api

docs/sdks/quickstart/browser.mdx
=> fix: browser quickstart doc

docs/guides/gettingStarted/k8s-deployment.mdx
/kind documentation
Fix the render of bash command blocks.
=> fix: bash command block

docs/guides/gettingStarted/nginxDomainConfig.mdx, i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/nginxDomainConfig.mdx
=> fix: v3.7 need nginx config

docs/guides/gettingStarted/jssdk.mdx, i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/jssdk.mdx
=> fix: update openim doc

docs/restapi/webhooks/group/applyJoinGroupBefore.mdx, docs/restapi/webhooks/group/setMemberInfoAfter.mdx, docs/restapi/webhooks/group/setMemberInfoBefore.mdx
=> fix:level type

docs/restapi/webhooks/group/memberJoinGroupBefore.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/memberJoinGroupBefore.mdx
docs: add memberJoinGroupBefore docs in webhook.
=> docs: add memberJoinGroupBefore docs in webhook.

docs/guides/gettingStarted/admin.mdx
Fixes #
feat: prometheus import path update
=> feat: prometheus import path update

docs/guides/gettingStarted/admin.mdx
=> fix: picture path

docs/guides/gettingStarted/admin.mdx
Fixes #
fix: add prometheus config edit illustrate
=> fix: add prometheus config edit illustrate

docs/guides/gettingStarted/nginxDomainConfig.mdx
=> fix: nginx minio url

docs/guides/gettingStarted/admin.mdx
Fixes #
fix: prometheus questions
=> fix: prometheus questions

docs/restapi/apis/userManagement/updateUserInfoEx.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateUserInfo.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateUserInfoEx.mdx
feat: update userInfoEx interface docs and update some comment.
=> feat: update userInfoEx interface docs and update some comment.

docs/restapi/apis/messageManagement/batchSendMessage.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/messageManagement/batchSendMessage.mdx
docs: update batch send message.
=> docs: update batch send message.

docs/restapi/apis/groupManagement/getRecvGroupApplicationList.mdx, docs/restapi/apis/groupManagement/getUserReqGroupApplicationList.mdx, docs/restapi/apis/groupManagement/groupApplicationResponse.mdx, docs/restapi/apis/groupManagement/muteGroupMember.mdx, docs/restapi/apis/groupManagement/quitGroup.mdx, docs/restapi/apis/groupManagement/setGroupInfoEX.mdx, docs/restapi/webhooks/group/setGroupInfoEXAfter.mdx, docs/restapi/webhooks/group/setGroupInfoEXBefore.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/groupManagement/getRecvGroupApplicationList.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/groupManagement/getUserReqGroupApplicationList.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/groupManagement/groupApplicationResponse.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/groupManagement/muteGroupMember.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/groupManagement/quitGroup.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/groupManagement/setGroupInfoEX.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/setGroupInfoEXAfter.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/setGroupInfoEXBefore.mdx
=> feat: add setGroupInfoEX interface

docs/restapi/apis/userManagement/updateUserInfoEx.mdx, docs/restapi/webhooks/user/updateUserInfoExAfter.mdx, docs/restapi/webhooks/user/updateUserInfoExBefore.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/groupManagement/setGroupInfoEX.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateUserInfoEx.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/updateUserInfoExAfter.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/updateUserInfoExBefore.mdx
=> docs: update user and group management API documentation

docs/restapi/webhooks/group/applyJoinGroupBefore.mdx, docs/restapi/webhooks/group/createAfter.mdx, docs/restapi/webhooks/group/createBefore.mdx, docs/restapi/webhooks/group/disMissGroupAfter.mdx, docs/restapi/webhooks/group/groupMsgRead.mdx, docs/restapi/webhooks/group/inviteJoinGroupBefore.mdx, docs/restapi/webhooks/group/joinGroupAfter.mdx, docs/restapi/webhooks/group/killGroupMember.mdx, docs/restapi/webhooks/group/memberJoinGroupBefore.mdx, docs/restapi/webhooks/group/quitGroup.mdx, docs/restapi/webhooks/group/sendGroupMsgAfter.mdx, docs/restapi/webhooks/group/sendGroupMsgBefore.mdx, docs/restapi/webhooks/group/setGroupInfoAfter.mdx, docs/restapi/webhooks/group/setGroupInfoBefore.mdx, docs/restapi/webhooks/group/setGroupInfoEXAfter.mdx, docs/restapi/webhooks/group/setGroupInfoEXBefore.mdx, docs/restapi/webhooks/group/setMemberInfoAfter.mdx, docs/restapi/webhooks/group/setMemberInfoBefore.mdx, docs/restapi/webhooks/group/transferGroupOwnerAfter.mdx, docs/restapi/webhooks/msg/msgModify.mdx, docs/restapi/webhooks/msg/sendSingleMsgAfter.mdx, docs/restapi/webhooks/msg/sendSingleMsgBefore.mdx, docs/restapi/webhooks/msg/singleMsgRead.mdx, docs/restapi/webhooks/msg/singleMsgRevokeAfter.mdx
=> feat: fix doc

docs/restapi/introduction.mdx, docs/restapi/webhooks/group/setGroupInfoAfter.mdx, docs/restapi/webhooks/user/updateUserInfoAfter.mdx
=> feat: server doc

docs/restapi/apis/authenticationManagement/getToken.mdx, docs/restapi/apis/authenticationManagement/getUserToken.mdx, docs/restapi/apis/userManagement/getUserIDList.mdx, docs/restapi/apis/userManagement/getUserOnlineStatus.mdx, docs/restapi/apis/userManagement/getUserOnlineStatusDetail.mdx, docs/restapi/apis/userManagement/subscribeUsersStatus.mdx, docs/restapi/introduction.mdx
=> docs: update docs.

docs/restapi/apis/userManagement/getUserOnlineStatus.mdx
=> fix: platformID

docs/restapi/apis/groupManagement/setGroupInfo.mdx
Fixes https://github.com/openimsdk/open-im-server/issues/2695
=> fix: group

docs/restapi/apis/userManagement/getSubscribeUsersStatus.mdx
=> docs: remove space.

docs/restapi/apis/userManagement/getSubscribeUsersStatus.mdx, docs/restapi/apis/userManagement/subscribeUsersStatus.mdx
=> docs: improve docs

i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/getFriendList.mdx, i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/getFriendListPage.mdx
=> fix: the return value problem of get friends list. (#205)

docs/guides/gettingStarted/dockerCompose.mdx
=> fix: docker

docs/restapi/apis/authenticationManagement/forceLogout.mdx, docs/sdks/callback/onKickedOffline.mdx, i18n/en/docusaurus-plugin-content-docs-sdks/current/callback/onKickedOffline.mdx
=> fix: update onKickedOffline docs

docs/restapi/webhooks/user/userRegisterAfter.mdx, i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/userRegisterAfter.mdx
Fixes #
fix: callback after register user remove secret
=> fix: callback after register user remove secret

i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/imSourceCodeDeployment.mdx
=> fix: wrong table format of section modify common config items

docs/guides/solution/developNewFeatures.mdx
=> feat: add doc about second development of server.

docs/guides/gettingStarted/cluster.mdx, docs/guides/gettingStarted/faq.mdx
=> feat: faq doc

docs/guides/solution/developNewFeatures.mdx
=> docs: update docs contents.

docs/guides/gettingStarted/internalDeployment.mdx
=> fix spelling mistake of "compose" in step 6
